services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GhidraDeforger
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    stdin_open: true
    tty: true

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: