services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GhidraHush
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
